<a href="https://colab.research.google.com/github/muhammadsajad/100_Days_of_Deep_Learning/blob/main/backpropagation_classification_ipunb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa','profile_score','placed'])

In [3]:
df.head()

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [12]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters={}
  L=len(layer_dims)

  for l in range(1,L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l],1))

  return parameters


In [18]:
# Utility Functions
def sigmoid(Z):

  A=1/(1+np.exp(-Z))
  return A

In [19]:
def linear_forward(A_prev,W,b):
  Z=np.dot(W.T, A_prev) + b

  A=sigmoid(Z)
  return A

In [20]:
# Forward prop
def L_layer_forward(X,parameters):
  A=X
  L=len(parameters)//2

  for l in range(1,L+1):
    A_prev=A
    Wl=parameters['W' + str(l)]
    bl=parameters['b' + str(l)]
    #print("A"+str(l-1)+": ",A_prev)
    #print("W"+str(l)+":",Wl)
    #print("b"+str(l)+":",bl)
    #print("--"*20)

    A=linear_forward(A_prev,Wl,bl)
    #print("A"+str(l)+":",A)
    #print("--"*20)


  return A,A_prev




In [33]:
# Updating the parameters using gradient descent algorithm
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0]=parameters['W2'][0][0] + (0.0001 * (y-y_hat)* A1[0][0])
  parameters['W2'][1][0]=parameters['W2'][1][0] + (0.0001 * (y - y_hat)) *A1[1][0]
  parameters['b2'][0][0]= parameters['W2'][1][0] + (0.0001 * (y-y_hat))

  parameters['W1'][0][0]=parameters['W1'][0][0] + (0.0001 *  (y - y_hat) * parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1]=parameters['W1'][0][1] + (0.0001 *  (y - y_hat) * parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0]= parameters['b1'][0][0] + (0.0001 * (y-y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0]= parameters['W1'][1][0] + (0.0001 * (y-y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1]=parameters['W1'][1][1] + (0.0001 * (y-y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0]=parameters['b1'][1][0] + (0.0001 * (y-y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))



In [34]:
# applying the whole process on first student
X=df[['cgpa','profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y=df[['placed']].values[0][0]

# Parameter initialization
parameters= initialize_parameters([2,2,1])

y_hat,A1=L_layer_forward(X,parameters)
y_hat=y_hat[0][0]
update_parameters(parameters,y,y_hat,A1,X)
print('Loss for this student -',-y*np.log(y_hat)-(1-y)*np.log(1-y_hat))
parameters

Loss for this student - 0.613402628898913


{'W1': array([[0.10000513, 0.10000513],
        [0.10000513, 0.10000513]]),
 'b1': array([[6.41054186e-07],
        [6.41054186e-07]]),
 'W2': array([[0.10003815],
        [0.10003815]]),
 'b2': array([[0.100084]])}

In [35]:
# Applying the whole process on second student
# applying the whole process on first student
X=df[['cgpa','profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training example)
y=df[['placed']].values[1][0]

# Parameter initialization
parameters= initialize_parameters([2,2,1])

y_hat,A1=L_layer_forward(X,parameters)
y_hat=y_hat[0][0]
update_parameters(parameters,y,y_hat,A1,X)
print('Loss for this student -',-y*np.log(y_hat)-(1-y)*np.log(1-y_hat))
parameters

Loss for this student - 0.613402628898913


{'W1': array([[0.10000449, 0.10000577],
        [0.10000449, 0.10000577]]),
 'b1': array([[6.41054186e-07],
        [6.41054186e-07]]),
 'W2': array([[0.10003815],
        [0.10003815]]),
 'b2': array([[0.100084]])}

In [36]:
# applying the whole process on third student
X=df[['cgpa','profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training example)
y=df[['placed']].values[2][0]

# Parameter initialization
parameters= initialize_parameters([2,2,1])

y_hat,A1=L_layer_forward(X,parameters)
y_hat=y_hat[0][0]
update_parameters(parameters,y,y_hat,A1,X)
print('Loss for this student -',-y*np.log(y_hat)-(1-y)*np.log(1-y_hat))
parameters

Loss for this student - 0.7798063059256977


{'W1': array([[0.09999546, 0.09999244],
        [0.09999546, 0.09999244]]),
 'b1': array([[-7.56487203e-07],
        [-7.56487203e-07]]),
 'W2': array([[0.09995495],
        [0.09995495]]),
 'b2': array([[0.0999008]])}

In [39]:
# epochs implementation
parameters = initialize_parameters([2,2,1])

epochs=5

for i in range(epochs):
  Loss=[]

  for j in range(df.shape[0]):

    X=df[['cgpa','profile_score']].values[j].reshape(2,1)
    y=df[['placed']].values[j][0]

    # parameter initializations

    y_hat,A1=L_layer_forward(X,parameters)
    y_hat=y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append(-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

  print('epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters






epoch -  1 Loss -  0.7103199085929446
epoch -  2 Loss -  0.6991702892802629
epoch -  3 Loss -  0.6991679314811485
epoch -  4 Loss -  0.6991655746710999
epoch -  5 Loss -  0.6991632188496667


{'W1': array([[0.09999445, 0.09998469],
        [0.09999445, 0.09998469]]),
 'b1': array([[-3.37225416e-06],
        [-3.37226502e-06]]),
 'W2': array([[0.09992227],
        [0.09992227]]),
 'b2': array([[0.09986615]])}

In [43]:
# Same Implemention but in Keras
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [44]:
model=Sequential()

model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))


In [45]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [47]:
model.get_weights()

[array([[-0.3262815 ,  0.9779092 ],
        [-0.91410536, -1.0313692 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.0852381],
        [ 1.0165988]], dtype=float32),
 array([0.], dtype=float32)]

In [51]:
new_weights=[np.array([[0.1 ,  0.1 ],
        [0.1, 0.1 ]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1],
        [ 0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]


In [52]:
model.set_weights(new_weights)

In [53]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [54]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [55]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values,epochs=50,verbose=1,batch_size=1)

Epoch 1/50
4/4 [==============================] - 1s 5ms/step - loss: 0.6952
Epoch 2/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6947
Epoch 3/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6941
Epoch 4/50
4/4 [==============================] - 0s 4ms/step - loss: 0.6940
Epoch 5/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6940
Epoch 6/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6939
Epoch 7/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6939
Epoch 8/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6939
Epoch 9/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6939
Epoch 10/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6939
Epoch 11/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6939
Epoch 12/50
4/4 [==============================] - 0s 4ms/step - loss: 0.6941
Epoch 13/50
4/4 [==============================] - 0s 4ms/step - loss: 0.