<a href="https://colab.research.google.com/github/muhammadsajad/100_Days_of_Deep_Learning/blob/main/Backpropagation_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])

In [ ]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [ ]:
# First we have to initialize the parameters and we have to provide acritecture to ur function
def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L=len(layer_dims)

  for l in range(1,L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l],1))

  return parameters


In [ ]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
def linear_forward(A_prev, W, b):
  Z=np.dot(W.T,A_prev)+b

  return Z

In [ ]:
# Forward prop
def L_layer_forward(X,parameters):
  A=X
  L=len(parameters)//2

  for l in range(1,L+1):
    A_prev=A
    Wl=parameters['W' + str(l)]
    bl=parameters['b' + str(l)]
    #print("A"+str(l-1)+": ",A_prev)
    #print("W"+str(l)+":",Wl)
    #print("b"+str(l)+":",bl)
    #print("--"*20)

    A=linear_forward(A_prev,Wl,bl)
    #print("A"+str(l)+":",A)
    #print("--"*20)


  return A,A_prev




In [ ]:
X=df[['cgpa','profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y=df[['lpa']].values[0][0]

# Parameter initialization
parameters= initialize_parameters([2,2,1])

y_hat,A1=L_layer_forward(X,parameters)

In [ ]:
y_hat

array([[0.32]])

In [ ]:
y_hat=y_hat[0][0]

In [ ]:
# Updating the parameters using gradient descent algorithm
def update_parameters(parameters,y,y_hat,A1,X):
  parameters["W2"][0][0]=parameters['W2'][0][0] + (0.001 *2 * (y-y_hat)* A1[0][0])
  parameters['W2'][1][0]=parameters['W2'][1][0] + (0.001 *2 * (y - y_hat)) *A1[1][0]
  parameters['b2'][0][0]= parameters['W2'][1][0] + (0.001 *2 * (y-y_hat))

  parameters['W1'][0][0]=parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1]=parameters['W1'][0][1] + (0.001 * 2 * (y-y_hat)* parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0]= parameters['b1'][0][0] + (0.001 * 2 * (y-y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0]= parameters['W1'][1][0] + (0.001 * 2 * (y-y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1]=parameters['W1'][1][1] + (0.001 * 2 * (y-y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0]=parameters['b1'][1][0] + (0.001 * 2 * (y-y_hat)*parameters['W2'][1][0])



In [ ]:
update_parameters(parameters,y,y_hat,A1,X)

In [ ]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [ ]:
X=df[['cgpa','profile_score']].values[1].reshape(2,1)
y=df[['lpa']].values[1][0]
y_hat,A1=L_layer_forward(X,parameters)

In [ ]:
update_parameters(parameters,y,y_hat,A1,X)

<ipython-input-11-95055c6651c3>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters["W2"][0][0]=parameters['W2'][0][0] + (0.001 *2 * (y-y_hat)* A1[0][0])
<ipython-input-11-95055c6651c3>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0]=parameters['W2'][1][0] + (0.001 *2 * (y - y_hat)) *A1[1][0]
<ipython-input-11-95055c6651c3>:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0]= parameters['W2'][1][0] + (0.001 *2 * (

In [ ]:
parameters


{'W1': array([[0.11458955, 0.1168776 ],
        [0.11458955, 0.1168776 ]]),
 'b1': array([[0.0019667],
        [0.0019667]]),
 'W2': array([[0.12712927],
        [0.12712927]]),
 'b2': array([[0.13612818]])}

In [ ]:
# epochs implementation
parameters = initialize_parameters([2,2,1])

epochs=5

for i in range(epochs):
  Loss=[]

  for j in range(df.shape[0]):

    X=df[['cgpa','profile_score']].values[j].reshape(2,1)
    y=df[['lpa']].values[j][0]

    # parameter initializations

    y_hat,A1=L_layer_forward(X,parameters)
    y_hat=y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters






epoch -  1 Loss -  25.321744156025517
epoch -  2 Loss -  18.320004165722047
epoch -  3 Loss -  9.473661050729628
epoch -  4 Loss -  3.2520938634031613
epoch -  5 Loss -  1.3407132589299962


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

In [ ]:
# Now doing the same thing in keras

import numpy as np
import pandas as pd

In [ ]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model=Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.get_weights()

[array([[-0.13558173,  0.6957052 ],
        [-0.07482874, -0.7816098 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.20931232],
        [ 0.3296932 ]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights=[np.array([[ 0.1,  0.1 ],
        [0.1,  0.1]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1 ],
        [0.48063898]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [ ]:
# Setting the our own new weights of created model
model.set_weights(new_weights)

In [ ]:
# Weights of the model after changing it
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1       ],
        [0.48063898]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer= keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [ ]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 1s 4ms/step - loss: 21.8021
Epoch 2/75
4/4 [==============================] - 0s 4ms/step - loss: 21.2580
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 20.7428
Epoch 4/75
4/4 [==============================] - 0s 4ms/step - loss: 20.2325
Epoch 5/75
4/4 [==============================] - 0s 4ms/step - loss: 19.7213
Epoch 6/75
4/4 [==============================] - 0s 4ms/step - loss: 19.2293
Epoch 7/75
4/4 [==============================] - 0s 4ms/step - loss: 18.7215
Epoch 8/75
4/4 [==============================] - 0s 6ms/step - loss: 18.1929
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 17.6712
Epoch 10/75
4/4 [==============================] - 0s 3ms/step - loss: 17.1696
Epoch 11/75
4/4 [==============================] - 0s 4ms/step - loss: 16.6138
Epoch 12/75
4/4 [==============================] - 0s 3ms/step - loss: 16.0602
Epoch 13/75
4/4 [==============================] - 0s 3ms/ste

In [ ]:
model.get_weights()

[array([[0.3184556 , 0.28354397],
        [0.3211253 , 0.28552783]], dtype=float32),
 array([0.22273529, 0.18696518], dtype=float32),
 array([[0.3237333],
        [0.6987999]], dtype=float32),
 array([0.17104162], dtype=float32)]